name: Continuous Integration
on: push

jobs:
  unit-test:
    name: Unit Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node:
          - 12
          - 14
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.os }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.os }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run lint
